name: Publish Package

on:
  push:
    tags:
      - "release-*"

jobs:
  publish-package:
    permissions:
      contents: write
      packages: write
    uses: ServerEmus/workflows/.github/workflows/package.yml@main
    with:
      ProjName: RENAME_ME
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
